@startuml
'https://plantuml.com/use-case-diagram

:Admin: as Admin
(Publiserer tur) as (Publiserer)
(Ordredetaljer) as (Ordre)
(Bruker søker etter tur) as (Søker)
(Bruker bestiller tur) as (Bestiller)
(Bekreftelse) as (bekreftelse)
(Bank transaksjon) as (Bank)

User --> (Søker)
(Søker) --> (Bestiller)
(Bestiller) --> (Ordre)
(Bestiller) ----> (bekreftelse)
Admin --> (bekreftelse)
(Bestiller) --> (Betaling)
(Betaling) --> (Bank)
(bekreftelse) -> (Kvittering)
(Betaling) -> (Kvittering)

Admin --> (Publiserer)
(Publiserer) --> (Ordre)
(Ordre) --> (Lokasjon)
(Ordre) --> (Pris)
(Ordre) --> (Antall)
(Ordre) --> (Tid)

@enduml
